import pandas as pd

FEATURE_COLUMNS = [
    "obd_available",
    "brand",
    "model",
    "engine_type",
    "engine_code",

    "rpm",
    "speed",
    "coolant_temp",
    "intake_temp",
    "throttle_pos",
    "engine_load",
    "map",
    "maf",
    "short_fuel_trim",
    "long_fuel_trim",
    "o2_voltage",
    "dtc_count",

    "symptom_power_loss",
    "symptom_hard_start",
    "symptom_rough_idle",
    "symptom_black_smoke",
    "symptom_blue_smoke",
    "symptom_white_smoke",
    "symptom_high_consumption",
    "symptom_check_engine",
    "symptom_engine_vibration",
    "symptom_misfire_feel",
    "symptom_stalls_idle",
    "symptom_overheating",
    "symptom_hard_start_hot",
    "symptom_hard_start_cold",
    "symptom_slow_acceleration",
    "symptom_fuel_smell",
     "symptom_rpm_fluctuation",
    "symptom_three_cylinders",
    "symptom_coolant_loss",
    "symptom_low_turbo_pressure",
    "symptom_turbo_whistle",
    "symptom_limp_mode",
    "symptom_no_throttle_response",
    "symptom_exhaust_smell_cabin",
    "symptom_hard_start_after_refuel",
    "symptom_weak_battery",
    "symptom_slow_crank",
    "symptom_alternator_not_charging",
    "symptom_battery_light",
    "symptom_fan_runs_often",
    "symptom_ac_affected",
    "symptom_temp_drops_while_driving",
    "symptom_slow_warmup",
    "symptom_timing_chain_noise",
    "symptom_accessory_belt_noise",
    "symptom_brake_vibration",
    "symptom_pulls_side",
    "symptom_abs_light",
    "symptom_esp_light",
    "symptom_high_adblue_consumption",
    "symptom_dpf_light",
    "symptom_frequent_dpf_regen",
    "symptom_sulfur_smell",
    "symptom_hard_shifting",
    "symptom_gearbox_jerks",   
    "symptom_oil_consumption",
    "symptom_metallic_noise",
    "symptom_brake_vibration",
    "symptom_pulls_side",
    "symptom_abs_light",
    "symptom_esp_light",
    "symptom_brake_squeal",
    "symptom_soft_brake_pedal",
    "symptom_steering_wheel_vibration",
    "symptom_noise_over_bumps",
    "symptom_wheel_knock",
    "symptom_steering_play",
    "symptom_pulls_when_braking",
]


def build_feature_frame(payload: dict) -> pd.DataFrame:
    row = {}

    for col in FEATURE_COLUMNS:
        row[col] = payload.get(col, 0)

    return pd.DataFrame([row])