SYMPTOM_OPTIONS = [
    "Lipsă putere",
    "Pornire grea",
    "Ralanti instabil",
    "Fum negru",
    "Fum albastru",
    "Fum alb",
    "Consum mare",
    "Check engine aprins",
    "Vibrații motor",
    "Rateuri",
    "Motorul se oprește la relanti",
    "Supraîncălzire",
    "Pornire grea la cald",
    "Pornire grea la rece",
    "Accelerație întârziată",
    "Miros puternic de combustibil",
    "Bătăi motor",
    "Zgomot metalic",
    "Pierdere ulei",
    "Miros de ars",
    "Pornire și oprire imediată",
    "Tremură la accelerație",
    "Consumă ulei",
    "Fum excesiv la accelerație",
    "Nu trage în sarcină",
    "Se îneacă la accelerație",
    "Turație oscilantă",
    "Motorul merge în 3 cilindri",
    "Pierdere antigel",
    "Presiune turbo scăzută",
    "Fluierat turbo",
    "Limp mode",
    "Pedală accelerație fără răspuns",
    "Miros gaze evacuare în habitaclu",
    "Pornire grea după alimentare",
    "Baterie slabă",
    "Electromotor învârte greu",
    "Alternator nu încarcă",
    "Martor baterie aprins",
    "Ventilator radiator pornește des",
    "Climatizare afectată",
    "Temperatura motorului scade în mers",
    "Motorul se încălzește greu",
    "Zgomot lanț distribuție",
    "Zgomot curea accesorii",
    "Tremură la frânare",
    "Mașina trage într-o parte",
    "ABS aprins",
    "ESP aprins",
    "Consum mare de AdBlue",
    "Martor DPF aprins",
    "Regenerări dese DPF",
    "Miros de sulf",
    "Cutie schimbă greu",
    "Smucituri la schimbarea vitezelor",
    "Consumă ulei",
    "Zgomot metalic",
    "Tremură la frânare",
    "Mașina trage într-o parte",
    "ABS aprins",
    "ESP aprins",
    "Scârțâit la frânare",
    "Pedală frână moale",
    "Volanul tremură",
    "Zgomot la denivelări",
    "Bătaie în roată",
    "Joc în volan",
    "Mașina trage la frânare",
]